version: '2'
services:
    scrapper:
        image: mongo
        build:
          context: .
        #   dockerfile: Dockerfile
        container_name: "scrapper"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
        volumes:
          - ./data/db:/data/db
        ports:
            - "27017:27017"
        command: mongod --logpath=/dev/null

